Repository URECA-Dapanda/dapanda-frontend, pull requests merged in 2025-08, with the labels that each got.

#208 [DP-240] feat: 채팅방 진입 시 memberId 기반 로직 개선 및 WebSocket 안정성 향상 #203
  src/feature/chat/api/chatRoomRequest.ts
  src/feature/chat/api/getChatHistory.ts
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatInputBar.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/types/chatType.ts
  src/feature/chat/utils/chatUtils.ts
  src/feature/chat/utils/groupMessagesByDate.ts
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/lib/time.ts
  src/stores/useWebSocketStore.ts
Labels: enhancement, FE, feature

#211 [DP-241] feat: 프로필 이미지 업로드 기능 구현 #205
  public/avatar-default.png
  src/components/common/AvatarIcon.tsx
  src/components/common/KakaoLoginButton.tsx
  src/components/common/header/SharedHeader.tsx
  src/feature/data/components/pages/DataItemContent.tsx
  src/feature/data/types/dataType.ts
  src/feature/mypage/apis/mypageRequest.ts
  src/feature/mypage/components/sections/profile/AvatarUploader.tsx
  src/feature/mypage/components/sections/profile/ProfileCard.tsx
  src/hooks/usePresignedUpload.ts
Labels: enhancement, FE, feature

#213 [DP-232] fix: fix data page mobile view
  public/dpd-logo-fit.svg
  src/app/(feature)/layout.tsx
  src/app/(feature)/mypage/layout.tsx
  src/app/api/auth/me/route.ts
  src/app/layout.tsx
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/components/common/button/SocialButton.tsx
  src/components/common/dropdown/UserDropdownMenu.tsx
  src/components/common/header/AppHeader.tsx
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/FullScreenModal.tsx
  src/components/common/navigation/BottomNavigation.tsx
  src/components/common/navigation/NavigationButton.tsx
  src/components/common/topsheet/TopSheet.tsx
  src/components/ui/dropdown-menu.tsx
  src/feature/chat/components/sections/room/ChatHeader.tsx
  src/feature/chat/components/sections/room/ChatInputBar.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/data/components/pages/DataPageContent.tsx
  src/feature/home/components/LandingPageContent.tsx
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/pages/MapPage.tsx
  src/feature/map/components/pages/MapSelectLocation.tsx
  src/feature/map/components/sections/product/MapBottomSheet.tsx
  src/feature/map/components/sections/product/MapContainer.tsx
  src/feature/map/components/sections/product/MapFloatingButtons.tsx
  src/feature/map/components/sections/regist/MapHeaderSearchBox.tsx
  src/feature/map/components/sections/regist/MapSelectedInfoCard.tsx
  src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
  tailwind.config.js
Labels: bug, FE, feature, style

#216 [DP-249] 배포 환경에서 지도 탭 진입 시 fetch 추가 #209
  src/feature/map/hooks/useMapInitializer.ts
Labels: bug, FE

#217 [DP-224] feat: FCM 알림 페이지 완성 #176
  src/app/(feature)/notification/page.tsx
  src/components/common/NotificationIcon.tsx
  src/feature/data/hooks/usePurchaseBuilder.ts
  src/feature/notification/api/requestNotification.ts
  src/feature/notification/components/pages/NotificationPageContent.tsx
  src/feature/notification/components/sections/NotificationCard.tsx
  src/feature/notification/components/sections/NotificationList.tsx
  src/feature/notification/utils/requestFcmToken.ts
Labels: enhancement, FE

#218 [DP-232] fix: data page mobile view
  src/app/(feature)/mypage/charge/fail/page.tsx
  src/app/(feature)/mypage/layout.tsx
  src/app/error/page.tsx
  src/app/not-found.tsx
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/FullScreenModal.tsx
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/components/pages/DataPageContent.tsx
  src/feature/data/components/pages/DefaultTabContent.tsx
  src/feature/map/components/pages/MapSelectLocation.tsx
  src/feature/map/components/sections/product/MapBottomSheet.tsx
  src/feature/map/components/sections/product/MapContainer.tsx
  src/feature/map/components/sections/regist/MapSelectedInfoCard.tsx
  src/feature/mypage/components/pages/ChargeFailPageContent.tsx
  src/feature/mypage/components/sections/charge/FailedMessage.tsx
  src/feature/mypage/components/sections/profile/DataStateComponent.tsx
  src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
  src/feature/payment/components/PaymentCompleteModal.tsx
  src/feature/payment/components/PaymentConfirmModal.tsx
  src/feature/payment/components/PaymentModal.tsx
Labels: bug, FE, feature, style

#223 [DP-243] feat: 가격 제한 추가
  src/feature/data/components/sections/modal/DataRegistModal.tsx
Labels: enhancement, FE

#230 [DP-260] fix: 프로필 및 탑시트 레이아웃 수정 #226
  src/app/(feature)/layout.tsx
  src/app/globals.css
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/mypage/components/pages/ReviewPageContent.tsx
Labels: bug, FE

#232 [DP-259] refactor: 사용자 정보 연동 및 WebSocket 연결 개선
  src/app/api/auth/me/route.ts
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/mypage/components/sections/LogOutButton.tsx
  src/hooks/useAuth.ts
  src/hooks/useWebSocketConnection.ts
  src/stores/useProfileStore.ts
Labels: FE

#236 [DP-232] fix: data page mobile view
  src/app/(feature)/@modal/default.tsx
  src/app/(feature)/@modal/review/page.tsx
  src/app/(feature)/chat/[chatRoomId]/layout.tsx
  src/app/(feature)/data/[postId]/layout.tsx
  src/app/(feature)/data/[postId]/page.tsx
  src/app/(feature)/layout.tsx
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/FullScreenModal.tsx
  src/components/common/modal/ReportModal.tsx
  src/components/common/topsheet/TopSheet.tsx
  src/feature/chat/components/pages/ChatListPageContent.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/data/components/pages/DataPageContent.tsx
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
  src/feature/mypage/components/sections/purchase/WriteReview.tsx
Labels: bug, style

#239 [MERGE] main 병합
  src/app/(feature)/@modal/default.tsx
  src/app/(feature)/@modal/review/page.tsx
  src/app/(feature)/chat/[chatRoomId]/layout.tsx
  src/app/(feature)/data/[postId]/layout.tsx
  src/app/(feature)/data/[postId]/page.tsx
  src/app/(feature)/layout.tsx
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/FullScreenModal.tsx
  src/components/common/modal/ReportModal.tsx
  src/components/common/topsheet/TopSheet.tsx
  src/feature/chat/components/pages/ChatListPageContent.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/data/components/pages/DataPageContent.tsx
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
  src/feature/mypage/components/sections/purchase/WriteReview.tsx
Labels: FE

#243 [DP-232] fix: fix notification page
  src/feature/notification/components/pages/NotificationPageContent.tsx
  src/feature/notification/components/sections/NotificationList.tsx
Labels: bug, FE, style

#244 [DP-264] fix: 구매가능/판매가능 뱃지 style 수정 #237
  src/components/common/badge/BadgeComponent.tsx
  src/components/common/badge/badgeVariants.ts
  src/feature/data/components/pages/DataDetailContent.tsx
Labels: FE, style

#245 [DP-260] feat: 모바일 바텀시트 스크롤 #226
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/feature/payment/components/PaymentCompleteModal.tsx
  src/feature/payment/hooks/usePaymentModals.tsx
  src/feature/payment/hooks/useWifiPurchaseBuilder.ts
  src/hooks/useLockBodyScroll.ts
Labels: enhancement, FE

#251 [DP-260] refactor: 바텀시트 스크롤 중첩 수정 #226
  src/components/common/bottomsheet/BaseBottomSheet.tsx
Labels: bug, FE

#259 [DP-259] fix: keyboard 스크롤 재반영 #225
  src/app/globals.css
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
Labels: bug

#260 [DP-260] fix: pc 환경에서 드래그 불가 수정 #226
  src/components/common/ProviderWrapper.tsx
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/stores/useWebSocketStore.ts
Labels: bug, FE

#262 [DP-270] fix: 자투리구매 price 계산 오류 수정 #258
  src/feature/data/api/scrapRecommendation.ts
  src/feature/data/components/sections/scrap/ScrapTabContent.tsx
  src/feature/data/hooks/useScrapRecommendation.ts
Labels: bug, FE

#263 [DP-232] fix: collapsible data
  src/app/(feature)/@modal/layout.tsx
  src/feature/data/components/sections/default/CollapsibleDataList.tsx
  src/feature/data/components/sections/default/DataItemCard.tsx
  src/feature/data/components/sections/filter/FilterCardContent.tsx
  src/feature/data/components/sections/filter/ScrapFilterCard.tsx
  src/feature/data/components/sections/scrap/ScrapTabContent.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
  src/feature/mypage/components/sections/profile/CurrentCashCard.tsx
Labels: bug, FE, feature, style

#267 [DP-275] feat: 판매완료 데이터는 수정,삭제 불가하도록 처리 #266
  public/0.png
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/types/dataType.ts
Labels: enhancement, FE

#269 [DP-277] fix: 프로필 이미지 업로드 후 UI 즉시 반영되도록 수정
  src/feature/mypage/components/sections/profile/AvatarUploader.tsx
Labels: bug, FE

#271 [DP-279] feat: 충전/환불 페이지 이탈 시 금액 초기화 처리 및 금액 0원 제한 #270
  src/feature/mypage/components/pages/CashActionContent.tsx
Labels: enhancement, FE

#273 [DP-259] refactor: 로그인 후 websocket 연결 로직 개선 및 인증 상태 처리 통합 #225
  src/apis/userProfile.ts
  src/hooks/useAuth.ts
  src/hooks/useWebSocketConnection.ts
  src/lib/axios.ts
  src/stores/useProfileStore.ts
  src/stores/useWebSocketStore.ts
Labels: FE

#277 [DP-283] refactor: 채팅방 진입 및 유틸 분리 리팩토링 #274
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatPostCard.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/utils/headerHeightDetection.ts
  src/feature/chat/utils/keyboardDetection.ts
  src/feature/chat/utils/messageProcessing.ts
  src/feature/chat/utils/productCache.ts
  src/feature/chat/utils/readStatusHandler.ts
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/seller/MapProfileCard.tsx
Labels: enhancement, FE, feature

#281 [DP-280] fix scroll error
  src/feature/data/components/sections/default/CollapsibleDataList.tsx
Labels: bug

#283 [DP-291] feat: 토스모달 스크롤 추가 #280
  src/feature/mypage/components/pages/CashActionContent.tsx
  src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
Labels: bug, FE

#284 [DP-280] fix bottom sheet scrolling
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/feature/mypage/components/sections/TransactionHistory.tsx
  src/feature/mypage/components/sections/profile/CurrentCashCard.tsx
Labels: bug

#290 [DP-297] fix: toss widjet 재오픈 시 렌더링 안되는 오류 수정 #289
  src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
Labels: bug, FE

#293 [DP-298] feat: 보유캐시 부족시 충전페이지로 리다이렉트 #291
  src/feature/mypage/components/sections/profile/SelectCharge.tsx
  src/feature/payment/hooks/usePaymentModals.tsx
Labels: enhancement, FE

#294 [DP-253] feat: 와이파이 타이머 추가 #215
  src/feature/map/components/sections/product/MapBottomSheet.tsx
  src/hooks/useAuth.ts
Labels: bug, FE

#309 [DP-266] feat: onboarding 구현 #241
  public/onboarding1.svg
  public/onboarding2.svg
  public/onboarding3.svg
  public/onboarding4.svg
  public/onboarding5.svg
  src/apis/userProfile.ts
  src/app/onboarding/page.tsx
  src/components/common/onboarding/OnboardingLayout.tsx
  src/components/common/onboarding/index.ts
  src/components/common/onboarding/onboardingData.ts
  src/feature/data/components/pages/DataPageContent.tsx
Labels: enhancement, FE, feature

#315 [DP-317] fix: remove mixpanel setting #314
  package-lock.json
  package.json
  src/components/common/PageViewTracker.tsx
  src/components/common/ProviderWrapper.tsx
  src/lib/mixpanel.ts
Labels: bug, FE

#308 [DP-253] feat: 맵 바텀시트 시간 포맷팅 및 배포환경 테스트를 위한 콘솔로그 추가 #215
  src/components/common/ProviderWrapper.tsx
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/product/TimeSelector.tsx
  src/feature/map/stores/useMapStore.ts
  src/hooks/subscribeToTimerOnce.ts
  src/hooks/useAuth.ts
  src/hooks/useSubscribeTimer.ts
  src/stores/useWebSocketStore.ts
  src/types/Alarm.ts
Labels: bug, enhancement, FE

#320 [DP-318] feat: 데이터 등록 실패 메시지 toast 출력 및 toast 한번만 뜨도록 수정 #316
  src/components/common/modal/ReportModal.tsx
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/sections/default/OverLimitAlert.tsx
  src/feature/data/components/sections/modal/DataRegistModal.tsx
  src/feature/data/hooks/useRegisterDataProduct.ts
  src/feature/data/hooks/useUpdateDataProduct.ts
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/list/MapListVirtual.tsx
  src/feature/map/components/sections/product/MapFloatingButtons.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
  src/feature/map/components/sections/seller/MapProfileCard.tsx
  src/feature/map/hooks/useMapInitializer.ts
  src/feature/mypage/components/pages/CashActionContent.tsx
  src/feature/mypage/components/sections/profile/AvatarUploader.tsx
  src/feature/mypage/hooks/useHandleTossSuccess.ts
  src/feature/mypage/hooks/useTossPayment.ts
  src/feature/payment/hooks/usePaymentModals.tsx
  src/lib/toast.ts
Labels: enhancement, FE

#317 [DP-315] fix: 채팅 입력창 전송 버튼 상태 및 메시지 전송 로직 개선
  src/components/common/ProviderWrapper.tsx
  src/components/common/input/InputComponent.tsx
  src/components/common/navigation/BottomNavigation.tsx
  src/components/ui/input.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatInputBar.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/stores/useChatStore.ts
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/stores/useWebSocketStore.ts
Labels: enhancement, FE, feature

#328 [DP-325] feat: postcard 와이파이 첫 번째 이미지 받아오는걸로 구현
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatPostCard.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/utils/productCache.ts
Labels: enhancement, FE, feature

#326 [DP-324] refactor: 채팅 로딩 지연 처리 및 아바타 우선 렌더링 적용
  src/app/layout.tsx
  src/components/common/AvatarIcon.tsx
  src/components/common/ProviderWrapper.tsx
  src/feature/chat/components/ChatContainer.tsx
Labels: enhancement, FE

#339 [DP-327] feat: jest 설정 및 데이터 판매/등록, 거래 로직에 대한 테스트 코드 추가 #330
  babel.config.js
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/app/layout.tsx
  src/feature/data/api/dataRequest.ts
  src/mocks/server.ts
  tests/feature/data/DataRegistModal.test.tsx
  tests/feature/data/dataRequest.test.ts
  tests/feature/data/scrapRecommendation.test.ts
  tests/feature/data/useScrapRecommendation.test.tsx
  tests/feature/payment/paymentRequest.test.ts
Labels: enhancement, FE

#344 [DP-164] feat: 현재 이용 가능 스크롤 수정 #126
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/sections/product/MapBottomSheet.tsx
Labels: enhancement, FE

#343 [DP-335] fix: hotfix remove unfitted requests
  src/app/api/auth/me/route.ts
  src/components/common/FcmInitializer.tsx
  src/feature/chat/components/ChatContainer.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/components/sections/modal/DataRegistModal.tsx
  src/feature/data/hooks/usePriceRecommendation.ts
  src/feature/notification/utils/requestFcmToken.ts
  src/hooks/useAuth.ts
Labels: bug, FE

#348 [DP-338] docs: update readme #342
  README.md
Labels: documentation, FE
