Repository URECA-Dapanda/dapanda-frontend, pull requests merged in 2025-07, with the labels that each got.

#18 [DP-41] feat: input 컴포넌트 구현 #13
  src/app/map/page.tsx
  src/components/common/input/InputComponent.tsx
  tailwind.config.js
Labels: enhancement, FE

#15 [DP-40] feat: 버튼 컴포넌트 구현 #11
  src/app/chat/page.tsx
  src/components/common/KakaoLoginButton.tsx
  src/components/common/button/ButtonComponent.tsx
  src/components/common/button/button.types.ts
  src/components/common/button/buttonVariants.ts
  src/components/common/button/index.ts
  src/components/common/search/AdvancedFilters.tsx
  src/components/common/search/SearchBar.tsx
  src/components/common/search/SearchFilter.tsx
  src/components/common/search/SortDropdown.tsx
  src/components/feature/chat/ChatContent.tsx
  src/components/ui/button.tsx
Labels: enhancement

#25 [DP-44] feat: badge 컴포넌트 구현 #16
  src/components/common/badge/BadgeComponent.tsx
  src/components/common/badge/badge.types.ts
  src/components/common/badge/badgeVariants.ts
  src/components/common/badge/index.ts
  src/components/feature/chat/ChatContent.tsx
  src/components/ui/badge.tsx
Labels: enhancement

#26 [DP-49] feat: item card component component development
  public/creditIcon.png
  src/components/common/card/CardComponent.tsx
  src/components/common/card/CardContentComponent.tsx
  src/components/common/card/FlatCard.tsx
  src/components/common/card/InfoCard.tsx
  src/components/common/card/ItemCard.tsx
  src/feature/chat/api/chatRequest.ts
  src/feature/chat/components/sample
  src/feature/chat/components/sections/ContentInfoCard.tsx
  src/feature/chat/types/contentType.ts
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/DataPageContent.tsx
  src/feature/data/components/sample
  src/feature/data/components/sections/filter/FilterCard.tsx
  src/feature/data/components/sections/filter/FilterCardContent.tsx
  src/feature/data/components/sections/product/DataItemCard.tsx
  src/feature/data/components/sections/product/DataItemContent.tsx
  src/feature/data/types/dataType.ts
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/sample
  src/feature/map/components/sections/product/MapItemCard.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/regist/SelectTypeCard.tsx
  src/feature/map/components/sections/regist/SelectTypeContent.tsx
  src/feature/map/types/mapType.ts
  src/feature/mypage/components/sample
  src/feature/mypage/components/sections/CurrentCashCard.tsx
Labels: enhancement, FE

#35 [DP-45] feat: Bottomsheet 공통 컴포넌트 구현 #19
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/map/page.tsx
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/components/common/bottomsheet/BottomSheetHeader.tsx
  src/components/common/bottomsheet/index.ts
Labels: enhancement, FE

#30 [DP-47] feat: tabs 공통 컴포넌트 #20
  components.json
  src/app/(home)/page.tsx
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/common/tabs/PurchaseTabs.tsx
  src/components/common/tabs/SalesHistoryTabs.tsx
  src/components/common/tabs/SlidingTabs.tsx
  src/components/common/tabs/index.tsx
  src/components/common/tabs/tabsConfig.ts
  src/components/common/tabs/useMultiRef.ts
  src/components/common/tabs/useSlidingHighlight.ts
  src/components/ui/tabs.tsx
Labels: enhancement, FE

#44 [DP-60] feat: input form 구현 #43
  src/app/map/page.tsx
  src/components/common/badge/badgeVariants.ts
  src/components/common/input/InputComponent.tsx
  src/components/ui/input.tsx
  src/feature/map/components/sections/regist/HotspotRegisterForm.tsx
  tailwind.config.js
Labels: enhancement, FE

#45 [DP-58] feat: develop-List
  package-lock.json
  package.json
  src/components/common/list/CollapseVirtualizedList.tsx
  src/components/common/list/VirtualizedInfiniteList.tsx
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/DataPageContent.tsx
  src/feature/map/api/mapRequest.ts
  src/hooks/sample
  src/hooks/useVirtualizedInfiniteQuery.ts
Labels: enhancement, FE

#55 [DP-67] docs: README.md 작성 #52
  README.md
Labels: documentation, FE

#62 [DP-73] feat: 채팅 목록 및 상세 페이지 초기 UI 구현 #58
  public/logo.svg
  src/app/chat/[chatId]/page.tsx
  src/app/chat/page.tsx
  src/components/common/card/ContentInfoCard.tsx
  src/components/common/header/LogoHeader.tsx
  src/feature/chat/api/chatRequest.ts
  src/feature/chat/components/ChatPageContent.tsx
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/components/sections/room/ChatRoomHeader.tsx
  src/feature/chat/hooks/sample
  src/feature/chat/hooks/useChatStream.ts
Labels: enhancement

#70 [DP-70] 모바일 데이터 상품 조회/상세 페이지 API 연동 테스트 및 컴포넌트 구현
  public/1.5.png
  public/1.8.png
  public/300.png
  src/app/data/[postId]/page.tsx
  src/app/data/layout.tsx
  src/app/data/page.tsx
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/DataDetailContent.tsx
  src/feature/data/components/DataPageContent.tsx
  src/feature/data/components/sections/DefaultTabContent.tsx
  src/feature/data/components/sections/ProfileCard.tsx
  src/feature/data/components/sections/product/CollapsibleDataList.tsx
  src/feature/data/components/sections/product/DataItemCard.tsx
  src/feature/data/types/dataType.ts
  src/feature/data/utils/dataMapper.ts
  src/lib/axios.ts
  src/lib/time.ts
Labels: enhancement

#72 [DP-82]feat: implement-mypage-history-page
  src/app/data/layout.tsx
  src/app/mypage/(history)/layout.tsx
  src/app/mypage/(history)/purchase-history/page.tsx
  src/app/mypage/(history)/sale-history/page.tsx
  src/components/common/button/buttonVariants.ts
  src/components/common/card/ItemCard.tsx
  src/components/common/container/LayoutBox.tsx
  src/components/common/list/VirtualizedInfiniteList.tsx
  src/components/common/rating/RatingScore.tsx
  src/components/common/tabs/PurchaseTabs.tsx
  src/components/common/tabs/SalesHistoryTabs.tsx
  src/components/common/tabs/SlidingTabs.tsx
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/DataPageContent.tsx
  src/feature/data/components/sections/DefaultTabContent.tsx
  src/feature/data/utils/dataMapper.ts
  src/feature/home/components/LandingPageContent.tsx
  src/feature/mypage/apis/mypageRequest.ts
  src/feature/mypage/components/pages/ChargeCashContent.tsx
  src/feature/mypage/components/pages/MyPageContent.tsx
  src/feature/mypage/components/pages/PurchaseHistoryPageContent.tsx
  src/feature/mypage/components/pages/SaleHistoryPageContent.tsx
  src/feature/mypage/components/sections/TabTitle.tsx
  src/feature/mypage/components/sections/profile/ChargeInfoCard.tsx
  src/feature/mypage/components/sections/profile/CicularProgressBar.tsx
  src/feature/mypage/components/sections/profile/CurrentCashCard.tsx
  src/feature/mypage/components/sections/profile/ProfileCard.tsx
  src/feature/mypage/components/sections/profile/ProfileWithHistoryCard.tsx
  src/feature/mypage/components/sections/profile/SelectCharge.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryCard.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryList.tsx
  src/feature/mypage/components/sections/sale/HistoryCard.tsx
  src/feature/mypage/components/sections/sale/OnSaleTabContent.tsx
  src/feature/mypage/components/sections/sale/SaleStateTab.tsx
  src/feature/mypage/components/sections/sale/SoldoutTabContent.tsx
  src/feature/mypage/types/mypageTypes.ts
Labels: enhancement, FE, feature

#77 [DP-71] feat: data 페이지 자투리 구매 기능 및 UI 구현 #57
  src/feature/data/api/dataRequest.ts
  src/feature/data/api/scrapRecommendation.ts
  src/feature/data/components/DataPageContent.tsx
  src/feature/data/components/sections/DefaultTabContent.tsx
  src/feature/data/components/sections/ScrapEmptyState.tsx
  src/feature/data/components/sections/ScrapLoadingState.tsx
  src/feature/data/components/sections/ScrapTabContent.tsx
  src/feature/data/components/sections/filter/DefaultFilterCard.tsx
  src/feature/data/components/sections/filter/FilterCard.tsx
  src/feature/data/components/sections/filter/FilterCardContent.tsx
  src/feature/data/components/sections/filter/ScrapFilterCard.tsx
  src/feature/data/components/sections/product/CollapsibleDataList.tsx
  src/feature/data/components/sections/product/DataItemCard.tsx
  src/feature/data/hooks/sample
  src/feature/data/hooks/useScrapRecommendation.ts
  src/feature/data/types/dataType.ts
  src/feature/data/types/scrapTypes.ts
  src/lib/axios.ts
Labels: enhancement, FE

#87 [DP-100] feat: 채팅 입력창 구현 및 메시지 상태 관리 로직 추가 #81
  src/app/chat/[chatId]/page.tsx
  src/app/chat/layout.tsx
  src/app/layout.tsx
  src/components/common/input/InputComponent.tsx
  src/components/common/navigation/ConditionalBottomNav.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatInputBar.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
Labels: enhancement, FE

#92 [DP-93] feat: implement-mypage-Review-page
  src/app/chat/(default)/layout.tsx
  src/app/chat/(default)/page.tsx
  src/app/chat/[chatId]/layout.tsx
  src/app/chat/review/layout.tsx
  src/app/chat/review/page.tsx
  src/app/data/layout.tsx
  src/app/data/review/layout.tsx
  src/app/data/review/page.tsx
  src/app/layout.tsx
  src/app/map/review/layout.tsx
  src/app/map/review/page.tsx
  src/app/mypage/review/layout.tsx
  src/app/mypage/review/page.tsx
  src/components/common/button/SocialButton.tsx
  src/components/common/card/CardComponent.tsx
  src/components/common/card/CardContentComponent.tsx
  src/components/common/card/ItemCard.tsx
  src/components/common/container/LayoutBox.tsx
  src/components/common/list/VirtualizedInfiniteList.tsx
  src/components/common/navigation/BottomNavigation.tsx
  src/components/common/navigation/ConditionalBottomNav.tsx
  src/components/common/tabs/ReviewTabs.tsx
  src/components/common/tabs/SlidingTabs.tsx
  src/components/common/tabs/tabsConfig.ts
  src/components/common/tabs/useSlidingHighlight.ts
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/sections/product/DataItemContent.tsx
  src/feature/home/components/LandingPageContent.tsx
  src/feature/mypage/apis/reviewRequest.ts
  src/feature/mypage/components/pages/PurchaseHistoryPageContent.tsx
  src/feature/mypage/components/pages/ReviewPageContent.tsx
  src/feature/mypage/components/pages/SaleHistoryPageContent.tsx
  src/feature/mypage/components/sections/TabTitle.tsx
  src/feature/mypage/components/sections/profile/ProfileCard.tsx
  src/feature/mypage/components/sections/profile/ProfileWithHistoryCard.tsx
  src/feature/mypage/components/sections/profile/SelectCharge.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryCard.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryList.tsx
  src/feature/mypage/components/sections/review/ReviewCard.tsx
  src/feature/mypage/components/sections/review/ReviewItem.tsx
  src/feature/mypage/components/sections/review/ReviewList.tsx
  src/feature/mypage/components/sections/review/SellingList.tsx
  src/feature/mypage/components/sections/sale/HistoryCard.tsx
  src/feature/mypage/components/sections/sale/OnSaleTabContent.tsx
  src/feature/mypage/components/sections/sale/SoldoutTabContent.tsx
  src/feature/mypage/types/reviewType.ts
  src/hooks/useProfile.ts
Labels: enhancement, FE, feature

#102 [DP-96] Feat: Toss payments로 캐시 충전 결제 구현 #78
  package-lock.json
  package.json
  src/app/mypage/charge/success/layout.tsx
  src/app/mypage/charge/success/page.tsx
  src/app/mypage/layout.tsx
  src/feature/mypage/apis/payment.ts
  src/feature/mypage/components/pages/ChargeCashContent.tsx
  src/feature/mypage/components/pages/MyPageContent.tsx
  src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
  src/feature/mypage/components/sections/toss/TossSuccessModal.tsx
  src/feature/mypage/hooks/sample
  src/feature/mypage/hooks/useHandleTossSuccess.ts
  src/feature/mypage/hooks/useTossPayment.ts
  src/feature/mypage/stores/sample
  src/feature/mypage/stores/useTossModalStore.ts
  src/feature/mypage/stores/useTossSuccessModalStore.ts
  src/feature/mypage/types/modalTypes.ts
Labels: enhancement, FE

#103 [DP-99] feat: 와이파이 상품 조회 api 구현 #80
  src/components/common/topsheet/WifiTopSheetContent.tsx
  src/feature/map/api/getMapDetailById.ts
  src/feature/map/api/mapRequest.ts
  src/feature/map/api/useSellerProfileQuery.ts
  src/feature/map/components/MapPageContent.tsx
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/list/MapListVirtual.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/seller/MapProfileCard.tsx
  src/feature/map/components/sections/seller/SellerSection.tsx
  src/feature/map/hooks/useMapDetailData.ts
  src/feature/map/hooks/useMapInfiniteQuery.ts
  src/feature/map/hooks/useMapInitializer.ts
  src/feature/map/types/mapType.ts
  src/feature/map/types/sellerType.ts
Labels: enhancement, FE

#97 [DP-118] feat: 채팅하기 버튼과 채팅방 연결 구현
  package-lock.json
  package.json
  src/app/chat/(default)/page.tsx
  src/app/chat/[chatId]/page.tsx
  src/app/chat/[chatRoomId]/layout.tsx
  src/app/chat/[chatRoomId]/page.tsx
  src/feature/chat/api/chatContentRequest.ts
  src/feature/chat/api/chatRequest.ts
  src/feature/chat/api/chatRoomRequest.ts
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatPostCard.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/hooks/useChatStream.ts
  src/feature/chat/stores/sample
  src/feature/chat/stores/useChatStore.ts
  src/feature/chat/types/chatType.ts
  src/feature/chat/utils/chatSocket.ts
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/lib/axios.ts
  src/lib/mock/map.ts
Labels: enhancement, FE

#111 [DP-141] feat: 분할판매글 뱃지 추가 및 경로 업데이트
  src/components/common/topsheet/PostTopSheetContent.tsx
  src/components/common/topsheet/topSheet.types.ts
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/components/pages/DataItemContent.tsx
  src/feature/data/components/sections/default/DataItemCard.tsx
  src/feature/data/types/dataType.ts
  src/feature/data/utils/dataMapper.ts
Labels: enhancement, FE

#122 [DP-158] feat: add-get-user-info
  src/feature/mypage/apis/mypageRequest.ts
  src/feature/mypage/components/sections/profile/CurrentCashCard.tsx
Labels: enhancement, FE, feature

#127 [DP-149] 채팅 웹소켓 연결 및 채팅방 기능 구현 #112
  package-lock.json
  package.json
  src/apis/chat.ts
  src/app/chat/(default)/page.tsx
  src/app/chat/[chatRoomId]/page.tsx
  src/components/common/card/ContentInfoCard.tsx
  src/components/common/input/InputComponent.tsx
  src/feature/chat/api/chatContentRequest.ts
  src/feature/chat/api/chatRoomRequest.ts
  src/feature/chat/api/getChatHistory.ts
  src/feature/chat/components/pages/ChatListPageContent.tsx
  src/feature/chat/components/pages/ChatRoomPageContent.tsx
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatInputBar.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/components/sections/room/ChatRoomHeader.tsx
  src/feature/chat/stores/useChatStore.ts
  src/feature/chat/types/chatType.ts
  src/feature/chat/types/contentType.ts
  src/feature/chat/types/message.ts
  src/feature/chat/utils/chatSocket.ts
  src/feature/chat/utils/groupMessagesByDate.ts
  src/feature/map/api/getMapDetailById.ts
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/product/MapBottomSheet.tsx
  src/feature/map/components/sections/product/MapContainer.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/hooks/useMapDetailData.ts
  src/feature/map/hooks/useMapMarkers.ts
  src/feature/map/types/mapType.ts
Labels: enhancement, FE

#136 [DP-135] feat: map 와이파이 업로드 기능 구현 #104
  next.config.ts
  src/components/common/topsheet/TopSheet.tsx
  src/components/common/topsheet/WifiTopSheetContent.tsx
  src/components/common/topsheet/useTopSheetExpanded.ts
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/pages/MapSelectLocation.tsx
  src/feature/map/components/pages/RegistLocation.tsx
  src/feature/map/components/sections/product/MapBottomSheet.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/regist/AddressMap.tsx
  src/feature/map/components/sections/regist/BasicInfoFields.tsx
  src/feature/map/components/sections/regist/ImageUploader.tsx
  src/feature/map/components/sections/regist/RegisterForm.tsx
  src/feature/map/hooks/usePostWifiRegister.ts
  src/feature/map/hooks/useRegisterFormState.ts
  src/feature/map/hooks/useWifiPriceRecommendation.ts
  src/feature/map/types/mapType.ts
  src/feature/map/types/registerForm.ts
  src/hooks/usePresignedUpload.ts
Labels: enhancement, FE

#140 [DP-135] fix: merge myProduct #104
  src/feature/map/components/pages/MapDetailPage.tsx
Labels: bug

#141 Feat/dp 171 add mypage api
  src/apis/userProfile.ts
  src/app/layout.tsx
  src/components/common/AvatarIcon.tsx
  src/components/common/button/SocialButton.tsx
  src/components/common/header/HeaderCash.tsx
  src/components/common/tabs/ReviewTabs.tsx
  src/components/common/tabs/tabsConfig.ts
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/components/sections/default/ProfileCard.tsx
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/seller/MapProfileCard.tsx
  src/feature/map/components/sections/seller/SellerSection.tsx
  src/feature/mypage/apis/mypageRequest.ts
  src/feature/mypage/apis/reviewRequest.ts
  src/feature/mypage/components/pages/MyPageContent.tsx
  src/feature/mypage/components/sections/HistoryButton.tsx
  src/feature/mypage/components/sections/TransactionHistory.tsx
  src/feature/mypage/components/sections/profile/CicularProgressBar.tsx
  src/feature/mypage/components/sections/profile/ProfileCard.tsx
  src/feature/mypage/components/sections/profile/ProfileWithHistoryCard.tsx
  src/feature/mypage/components/sections/review/ReviewCard.tsx
  src/feature/mypage/components/sections/review/ReviewList.tsx
  src/hooks/useVirtualizedInfiniteQuery.ts
  src/stores/useProfileStore.ts
  src/types/User.ts
Labels: enhancement, FE, feature

#145 [DP-175] feat: 데이터 게시글 수정하기 구현 #134
  src/feature/data/api/dataRequest.ts
  src/feature/data/components/pages/DataDetailContent.tsx
  src/feature/data/components/sections/modal/DataRegistModal.tsx
  src/feature/data/hooks/useDataDetail.ts
  src/feature/data/hooks/useRegisterDataProduct.ts
  src/feature/data/hooks/useUpdateDataProduct.ts
Labels: enhancement, FE, feature

#142 [DP-167] feat: review component
  src/app/map/layout.tsx
  src/app/map/review/register/layout.tsx
  src/app/map/review/register/page.tsx
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/feature/map/api/reviewRequest.ts
  src/feature/map/components/pages/ReviewRegistPage.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
  src/feature/map/components/sections/timer/TimerEndModal.tsx
  src/feature/map/hooks/useReviewMutation.ts
  src/feature/map/types/reviewType.ts
Labels: enhancement, FE

#148 [DP-178] feat: 와이파이 상품 구매 기능 API 연동 구현 #137
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/sections/product/TimeSelector.tsx
  src/feature/map/hooks/useMapDetailData.ts
  src/feature/map/hooks/useRegisterFormValidation.ts
  src/feature/map/types/mapType.ts
  src/feature/payment/api/paymentRequest.ts
  src/feature/payment/hooks/usePaymentModals.tsx
  src/feature/payment/hooks/useWifiPurchaseBuilder.ts
  src/feature/payment/types/paymentTypes.ts
  src/lib/time.ts
Labels: enhancement, FE

#150 Feat/dp 171 add mypage api
  src/feature/data/components/pages/DefaultTabContent.tsx
  src/feature/mypage/apis/mypageRequest.ts
  src/feature/mypage/components/sections/review/ReviewCard.tsx
  src/feature/mypage/components/sections/review/SellingList.tsx
  src/feature/mypage/components/sections/sale/HistoryCard.tsx
  src/feature/mypage/components/sections/sale/OnSaleTabContent.tsx
Labels: enhancement, FE, feature

#158 [DP-200] feat: 공통 Skeleton 컴포넌트 및 채팅/카드용 스켈레톤 UI 컴포넌트 구현 #156
  src/components/common/skeleton/SkeletonCard.tsx
  src/components/common/skeleton/SkeletonChatItem.tsx
  src/components/common/skeleton/index.ts
  src/components/ui/skeleton.tsx
Labels: enhancement, FE, feature

#162 [DP-202] feat: add current data value
  src/feature/mypage/components/pages/MyPageContent.tsx
  src/feature/mypage/components/sections/profile/CicularProgressBar.tsx
Labels: enhancement, FE, feature

#153 [DP-195] feat: 채팅방 상단 옵션 메뉴 및 프로필 보기 연동
  src/app/map/review/layout.tsx
  src/components/common/dropdown/dropdownConfig.ts
  src/feature/chat/components/sections/list/ChatItem.tsx
  src/feature/chat/components/sections/list/ChatList.tsx
  src/feature/chat/components/sections/room/ChatBubble.tsx
  src/feature/chat/components/sections/room/ChatPostCard.tsx
  src/feature/chat/components/sections/room/ChatRoomContent.tsx
  src/feature/chat/components/sections/room/ChatRoomHeader.tsx
  src/feature/chat/stores/useChatStore.ts
  src/feature/chat/types/chatType.ts
  src/feature/map/components/pages/ReviewRegistPage.tsx
  src/feature/map/components/sections/review/ReviewBottomSheet.tsx
Labels: enhancement, FE

#159 [DP-196] feat: 와이파이 등록 UI 개선 및 마커 클릭 시 정보 추가 #151
  src/app/map/regist/[type]/location/page.tsx
  src/app/map/regist/[type]/page.tsx
  src/components/common/topsheet/WifiTopSheetContent.tsx
  src/feature/map/api/mapRequest.ts
  src/feature/map/components/pages/MapDetailPage.tsx
  src/feature/map/components/pages/MapSelectLocation.tsx
  src/feature/map/components/pages/RegistLocation.tsx
  src/feature/map/components/sections/product/MapContainer.tsx
  src/feature/map/components/sections/product/MapFloatingButtons.tsx
  src/feature/map/components/sections/product/MapItemContent.tsx
  src/feature/map/components/sections/regist/AddressMap.tsx
  src/feature/map/components/sections/regist/BasicInfoFields.tsx
  src/feature/map/components/sections/regist/InteractiveMap.tsx
  src/feature/map/components/sections/regist/MapHeaderSearchBox.tsx
  src/feature/map/components/sections/regist/MapSelectedInfoCard.tsx
  src/feature/map/components/sections/regist/SelectTypeCard.tsx
  src/feature/map/hooks/useInteractiveMapMarker.ts
  src/feature/map/hooks/useMapDetailData.ts
  src/feature/map/hooks/useMapLocationSelector.ts
  src/feature/map/hooks/useMapMarkers.ts
  src/feature/map/hooks/useMapRefresh.ts
  src/feature/map/hooks/useMyLocation.ts
  src/feature/map/stores/useMapStore.ts
  src/feature/map/types/naverSearch.ts
  src/feature/map/utils/reverseGeocode.ts
Labels: enhancement, FE

#187 [DP-229] refactor: 모바일 화면 지도 위치 수정 #185
  src/app/(feature)/layout.tsx
  src/components/common/header/AppHeader.tsx
  src/components/common/navigation/BottomNavigation.tsx
  src/feature/map/components/pages/MapPage.tsx
  src/feature/map/components/sections/product/MapContainer.tsx
  src/feature/map/components/sections/product/MapFloatingButtons.tsx
  src/feature/map/components/sections/product/TimeSelector.tsx
  src/feature/map/components/sections/regist/SelectTypeCard.tsx
  src/feature/notification/utils/onForegroundMessage.ts
  src/hooks/useMapHeight.ts
Labels: enhancement, FE

#191 [DP-231] docs: 리드미 작성 #188
  README.md
Labels: documentation, FE

#196 [DP-224] feat: FCM 알림 appheader에 추가 #176
  src/components/common/header/AppHeader.tsx
  src/feature/notification/utils/requestFcmToken.ts
Labels: enhancement, FE

#197 [DP-235] fix: fix mypage
  src/components/common/bottomsheet/BaseBottomSheet.tsx
  src/feature/mypage/components/pages/MyPageContent.tsx
  src/feature/mypage/components/sections/profile/CicularProgressBar.tsx
  src/feature/mypage/components/sections/profile/DataStateComponent.tsx
  src/feature/mypage/components/sections/profile/ProfileWithHistoryCard.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryCard.tsx
  src/feature/mypage/components/sections/purchase/PurchaseHistoryList.tsx
  src/feature/mypage/components/sections/sale/HistoryCard.tsx
  src/feature/mypage/types/mypageTypes.ts
Labels: enhancement, FE, feature

#202 [DP-239] feat: Hotjar 추적 스크립트 추가 및 설치 준비
  src/app/layout.tsx
Labels: FE

#204 [DP-224] feat: 알림 조회/삭제 API 연동 준비 #176
  src/feature/notification/api/postFcmToken.ts
  src/feature/notification/api/requestNotification.ts
  src/feature/notification/components/pages/NotificationPageContent.tsx
  src/feature/notification/components/sections/NotificationCard.tsx
  src/feature/notification/utils/requestFcmToken.ts
Labels: enhancement, FE
